version: "3"
services:
  db:
    image: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}" ]
    # command: ["postgres", "-c", "log_statement=all"]
    ports:
      - "5432:5432"
    networks:
      - bcn
    environment:
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=db
  bcn:
    build: .
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -f http://localhost:${PORT}/ || exit 1"
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    command: npm start
    ports:
      - "1031:1031"
    environment:
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=db
      - RPC_PROTOCOL=http
      - RPC_USER=${RPC_USER}
      - RPC_PASSWORD=${RPC_PASSWORD}
    working_dir: /dist
    depends_on:
      - db
    networks:
      - bitcoin
      - bcn
networks:
  bitcoin: null
  bcn: null
