version: "3"
services:
  db:
    env_file: .env
    volumes:
      - ./chain-setup/btc-mainnet/db-data:/var/lib/postgresql/data
      - ./db/db_schema.sql:/docker-entrypoint-initdb.d/db_schema.sql
  node:
    image: ruimarinho/bitcoin-core:23.0
    ports:
      - 8333:8333
      - 8332:8332
      - 28332:28332
    volumes:
      # using a custom path for data dir
      - ./chain-setup/btc-mainnet/blockchain-data:/home/bitcoin/.bitcoin
    networks:
      - bitcoin
    command:
      [
        "bitcoind",
        "-dbcache=4000",
        "-txindex=1",
        "-server=1",
        "-rpcbind=0.0.0.0",
        "-rpcworkqueue=512",
        "-rpcport=8332",
        "-port=8333",
        "-printtoconsole=1",
        "-zmqpubhashtx=tcp://0.0.0.0:28332",
        "-zmqpubrawtx=tcp://0.0.0.0:28332",
        "-rpcallowip=0.0.0.0/0",
        "-rpcauth=${RPC_AUTH}",
        "-wallet=${DEFAULT_WALLET}"
      ]
  bcn:
    build: .
    image: bitcoin-computer-node
    env_file: .env
    depends_on:
      - db
      - node
    environment:
      - BCN_ENV=prod
      - RPC_HOST=node
      - RPC_PORT=8332
      - ZMQ_URL=tcp://node:28332
      - NETWORK=mainnet
      - CHAIN=BTC
      - BCN_URL=http://127.0.0.1:1031
  sync:
    command: npm run sync
    build: .
    image: bitcoin-computer-node
    env_file: .env
    depends_on:
      - db
      - node
    environment:
      - BCN_ENV=prod
      - RPC_HOST=node
      - RPC_PORT=8332
      - NETWORK=mainnet
      - CHAIN=BTC
      - ZMQ_URL=tcp://node:28332
      - BCN_URL=http://127.0.0.1:1031
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=db
      - RPC_PROTOCOL=http
      - RPC_USER=${RPC_USER}
      - RPC_PASSWORD=${RPC_PASSWORD}
    networks:
      - bitcoin
      - bcn
