services:
  db:
    env_file: .env
    volumes:
      - ./chain-setup/ltc-mainnet/db-data:/var/lib/postgresql/data
      - ./db/db_schema.sql:/docker-entrypoint-initdb.d/db_schema.sql
    restart: always
  node:
    image: litecoinproject/litecoin-core:0.21
    networks:
      - bitcoin
    restart: always
    command:
      [
        "litecoind",
        "-dbcache=4000",
        "-txindex=1",
        "-server=1",
        "-rpcbind=0.0.0.0",
        "-rpcworkqueue=512",
        "-rpcport=9332",
        "-port=9335",
        "-zmqpubhashtx=tcp://0.0.0.0:28332",
        "-zmqpubrawtx=tcp://0.0.0.0:28332",
        "-rpcallowip=0.0.0.0/0",
        "-rpcauth=${RPC_AUTH}",
        "-wallet=${DEFAULT_WALLET}"
      ]
    ports:
      - 9333:9333
      - 9332:9332
      - 28332:28332
    volumes:
      - ./chain-setup/ltc-mainnet/blockchain-data:/home/litecoin/.litecoin
  bcn:
    #image: bcdb/bcn:0.9.12
    image: bitcoin-computer-node
    env_file: .env
    restart: always
    environment:
      - BCN_ENV=dev
      - RPC_HOST=node
      - RPC_PORT=9332
      - ZMQ_URL=tcp://node:28332
      - NETWORK=mainnet
      - CHAIN=LTC
      - BCN_URL=https://ltc.node.bitcoincomputer.io
    depends_on:
      - db
      - node
  sync:
    command: npm run sync
    # image: bcdb/bcn:0.9.12
    image: bitcoin-computer-node
    env_file: .env
    restart: always
    environment:
      - BCN_ENV=dev
      - RPC_HOST=node
      - RPC_PORT=9332
      - NETWORK=mainnet
      - CHAIN=LTC
      - ZMQ_URL=tcp://node:28332
      - BCN_URL=https://ltc.node.bitcoincomputer.io
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=db
      - RPC_PROTOCOL=http
      - RPC_USER=${RPC_USER}
      - RPC_PASSWORD=${RPC_PASSWORD}
      - THREADS=${THREADS}
    volumes:
      - ./logs:/dist/packages/node/logs
    depends_on:
      - db
      - node
    networks:
      - bitcoin
      - bcn
  